name: Release
on:
  push:
    tags: v*
permissions:
  contents: read
  id-token: write
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: node -v && npm -v
      - run: npm ci
      - run: npm publish --provenance --access public
